### ISSUE TITLE
Plastic centroid/principal axis centroid not at elastic centroid for doubly symmetric section

### ISSUE THREAD

**Issue by Agent6-6-6** [robbievanleeuwen/section-properties#38] opened 2020-12-19 18:51 UTC
**Describe the bug**
In the following code I would expect the plastic centroid to be at the origin (0, 0) and align with the elastic centroid. Yet it is reporting the plastic centroid below the origin. Section geometry centroid is shifted to 0,0 position.

Also, the horizontal principal axis is shown correctly at y=0, but the principal plastic axis centroid is not, being drawn below y=0.

The reported results agree with the plot in so far as the plastic centroid is not at 0,0 point.

Is this possibly a bug or maybe I'm missing something obvious here?

**To Reproduce**
Run code below and observe results

```
import sectionproperties.pre.sections as sections
from sectionproperties.analysis.cross_section import CrossSection

mesh_area = 25  # max mesh size

d = 612  # I section depth
b_f = 229  # I-section flange width
t_f = 19.6  # I-section flange thickness
t_w = 11.9  # I-section web thickness
r_1 = 14  # I-section root radii
n_r = 50  # number of points considered around root radii

d_p = 650  # strengthening plate depth
b_p = 12  # strengthening plate thickness

# create constituent geometry
geometry1 = sections.ISection(d=d, b=b_f, t_f=t_f, t_w=t_w, r=r_1, n_r=n_r, shift=[-b_f / 2, -d / 2])
geometry2 = sections.RectangularSection(d=d_p, b=b_p, shift=[-b_f / 2 - b_p, -d_p / 2])
geometry3 = sections.RectangularSection(d=d_p, b=b_p, shift=[b_f / 2, -d_p / 2])

# create merged section
geometry = sections.MergedSection([geometry1, geometry2, geometry3])

# add holes
geometry.add_hole([-b_f / 2, 0])
geometry.add_hole([b_f / 2, 0])

# create mesh
mesh = geometry.create_mesh(mesh_sizes=[mesh_area, mesh_area, mesh_area])

# clean geometry
geometry.clean_geometry(verbose=True)

# create section
section = CrossSection(geometry, mesh)

# calculate results
section.calculate_geometric_properties()
section.calculate_plastic_properties()
section.calculate_warping_properties()

# plot results
section.plot_mesh()
section.plot_centroids()

# display all results
# check https://sectionproperties.readthedocs.io/en/latest/rst/post.html for definitions
section.display_results(fmt='.3f')

# this will specifically display torsion and warping constants
J = section.get_j()
I_w = section.get_gamma()
print(f'J = {J}')
print(f'I_w = {I_w}')
```

**Expected behaviour**
For doubly symmetric section plastic and elastic centroid should align?

**Screenshots**
Note how principal plastic axis centroid does not align with the principal axes, and plastic centroid is shown below elastic centroid:-
![Figure_1](https://user-images.githubusercontent.com/36808164/102696973-213be380-4297-11eb-8929-8b7dfa4553bf.png)

**Additional context**
Using latest version 1.0.7

**Comment by Agent6-6-6** [comment] 2020-12-19 19:37
Ok I think I found the issue, the hole I was adding was on the edge of the side plates.

```
# add holes
geometry.add_hole([-b_f / 2, 0])
geometry.add_hole([b_f / 2, 0])
```
Should be 
```
# add holes
geometry.add_hole([-b_f / 3, 0])
geometry.add_hole([b_f / 3, 0])
```

Then you get the correct results. 

I guess this raises the issue that there should possibly be a check somewhere that the defined hole point does not lie on the edge of a defined geometry. As the results look plausible despite the error.

**Comment by Spectre5** [comment] 2020-12-19 21:03
Interesting, I wonder what the top one actually analyzed then?!  With one or neither hole being "recognized" as a hole, it still wouldn't have an elastic centroid in the middle and a plastic center just below it.

Perhaps a quick solution would be to add a small yellow or blue dot in these cross section views to indicate where the "holes" are, so that at least it would be quickly visible that the hole is close or on an edge.  Even better may to be shade the holes a really light/faded color (maybe light gray or light yellow) to indicate what was actually recognized as a hole.

**Comment by Spectre5** [comment] 2020-12-19 21:07
In the first example (with hole on the "edge"), I get the plastic centroid shifting up instead of down:

![Figure_1](https://user-images.githubusercontent.com/31610422/102699645-28adaf00-41fb-11eb-8aca-90aabb88fa2f.png)

**Comment by Spectre5** [comment] 2020-12-19 21:17
So, there is a plot_geometry that shows the holes:

    # clean geometry
    geometry.clean_geometry(verbose=True)
    geometry.plot_geometry()  # <--- ADDED THIS

which produces this:

![Figure_1](https://user-images.githubusercontent.com/31610422/102699767-2ac43d80-41fc-11eb-8800-90df356f861c.png)

But still, since it is easy to overlook this one and only look at the `plot_centroids` plot, I still wonder if the `plot_centroids` should also indicate the holes, even if just as an optional flag.  And regardless, I still like the idea of the "holes" being shaded to make it abundantly clear where the holes are actually identified.  @Agent6-6-6's suggestion of raising an exception is also a good idea.

**Comment by robbievanleeuwen** [comment] 2020-12-20 07:32
Interesting! I'll have a little dig and try to find out what's going on here. Will report back...

**Comment by robbievanleeuwen** [comment] 2020-12-20 10:41
So in short, placing a hole point directly on a facet confuses the mesh generation algorithm (_triangle_) a fair bit. I think it must come down to computer precision and storage of floats when triangle decides which side of the facet the hole is on - this explains why you both got mirrored answers. 

When _triangle_ meshes the cross-section as a whole, it gets it right and the computed section properties for the geometric and warping analyses are correct.

However when undertaking the plastic analysis, the algorithm remeshes the cross-section a number of times with varying plastic neutral axes. In this case, triangle 'guesses' wrong and places the hole in the side plate and thus you end up finding the plastic properties of an entirely different section. This can be visualised by enabling the option, _debug=True_ when running the plastic analysis. See below what the mesh looks like in one of the steps of the plastic analysis algorithm.

![Figure_1](https://user-images.githubusercontent.com/18841910/102711001-9e547080-430a-11eb-977e-b8e2c9f444af.png)

So what does this mean for _sectionproperties_?

1. Don't place a hole point on a facet! I think that this is a fairly obvious thing to avoid as, by definition, a hole cannot be defined on a facet of the geometry. Any attempts to do so is user error.
2. The suggestion of shading the holes is difficult to implement as the meshing algorithm does not give this to me so would involve a whole lot of work for minimal gain considering that...
3. What you see is what you get with the mesh plots. In the above centroid plot you are seeing the mesh that _sectionproperties_ has used to determine the geometric and warping properties. So showing a shaded area for hole regions would not add anything to these plots. Unfortunately the way the plastic algorithm works involves creating a new mesh for every loop of the solver and unless requesting by the user by selecting _debug=True_, will be hidden.

My feeling is that while this is a strange artefact of the meshing algorithm, it is not a bug and is the result of user error. I believe that there are sufficient tools available to detect this error i.e. _plot_geometry()_ shows that the hole points lie on facets. The only way for the user to pick this input error up would be for the user to inspect every single mesh generated by the plastic algorithm and there exists is this possibility with the _debug=True_ option. 

Keen to hear both your thoughts on this one and whether or not you agree with my approach before we close this one out @Agent6-6-6  @Spectre5

Thanks again for picking this one up!

**Comment by Spectre5** [comment] 2020-12-20 23:57
I agree that it is basically user error and I can appreciate the difficulty in trying to shade things.  Future, I didn't realize that there were the multiple re-meshes happening with the plastic method, which complicates things.

Perhaps it would still make sense to compute the distance between each hole and each "edge" of the geometry though.  Then either give a warning or raise an exception if it is within some tolerance?  I can potentially take a stab at that if you'd be interested in adding it and don't have the time.

**Comment by robbievanleeuwen** [comment] 2020-12-21 02:01
That's not a bad idea. Could be implemented as a validation check before the cross-section is meshed. I guess it's just loop through every hole point and facet point and check that they don't coincide - bit of a geometry algorithm. If you are interested in having a go at it I'd be happy to merge into the program and assist if needed.

**Comment by Agent6-6-6** [comment] 2020-12-21 07:15
Agree, I always find it useful to protect the user against themselves..... by providing sufficient warnings when stuff matters.

If you're already using shapely and moving that way you can check for "touching" geometry as follows:-

```
from shapely.geometry import Point, Polygon

a = Point([0, 0.5])
b = Polygon([(0, 0), (0, 1), (1, 1), (1, 0), (0, 0)])
c = Point([2, 2])
print(a.touches(b))
print(c.touches(b))
```

Probably the easiest way to implement the intersection check.

**Comment by Spectre5** [comment] 2020-12-21 08:07
I've added a PR that should add this check, but it is not nearly as clean looking as what @Agent6-6-6 posted above :)  It does do the entire calculation vectorized in numpy though, so it should be much faster than looping in python though.

**Closed** 2021-01-03 00:38 UTC
Labels: bug
