### ISSUE TITLE
Area counted twice in plastic algorithm

### ISSUE THREAD

**Issue by robbievanleeuwen** [robbievanleeuwen/section-properties#193] opened 2022-02-17 09:10 UTC
I have come across a case where the plastic algorithm can count an area twice and affect the plastic properties. See below example:

```python
import sectionproperties.pre.library.primitive_sections as ps
from sectionproperties.analysis.section import Section

rect1 = ps.rectangular_section(d=600, b=300)
rect2 = ps.rectangular_section(d=100, b=100).shift_section(100, 450)
geom = rect1 + rect2
geom.create_mesh(100)
geom.plot_geometry()

sec = Section(geom)
sec.plot_mesh()

sec.calculate_geometric_properties()
print(sec.get_area())

sec.calculate_plastic_properties()
print(sec.get_pc())
```

The section meshes as expected and the correct area is calculated (`area = 180000`), however I believe the `.split_section()` method used by the plastic algorithm returns geometries that overlap for the top half of the section (i.e. two boxes are returned from the method and there is no hole in the larger box to accomodate the smaller box). This results in a plastic centroid shifted up the section (`y_pc = 306.14`, expecting `y_pc = 300`).

This is not the expected behaviour and it would be great to get a fix to this as this results in the incorrect reporting of plastic properties.

**Comment by connorferster** [comment] 2022-02-17 15:22
Nice catch!

I will have to think about this one because it relates to modelling practice also. In my immediate understanding, this can be solved by subtracting the inner from the outer before combining. However, this is of course related to the nested geometries modelling example so I will have to check if the plastic properties are the same or not (I expect not) for the two approaches described.

**Comment by Agent6-6-6** [comment] 2022-02-19 05:48
this effectively solves the issue, so it is something to do with the compond geometry having both geometries and double counting?

```
import sectionproperties.pre.library.primitive_sections as ps
from sectionproperties.analysis.section import Section

rect1 = ps.rectangular_section(d=600, b=300)
rect2 = ps.rectangular_section(d=100, b=100).shift_section(0, 500)

geom1 = rect1 - rect2
geom = geom1 + rect2
geom.create_mesh(100)
geom.plot_geometry()
print(geom)
sec = Section(geom)
sec.plot_mesh()

sec.calculate_geometric_properties()
print(sec.get_area())
sec.calculate_plastic_properties()
print(sec.get_pc())
```

Gives both plastic centroids correctly.

**Comment by Agent6-6-6** [comment] 2022-02-19 07:05
@connorferster, as I noted at bottom :)

**_Gives both plastic centroids correctly._** 

I get the following for the plastic centroid 

```
(149.99999999999997, 299.99999999999994)```

**Comment by Agent6-6-6** [comment] 2022-02-19 08:40
I was using the intermediate variable geom and geom1 rather than just geom, it works as intended one way but not the other

**Comment by Agent6-6-6** [comment] 2022-02-19 18:52
Just to clarify, I realised I stuffed up on the first example I mentioned where it did not work as I had just redefined geom back to the original example... instead of doing further manipulation of geom!

To explain, this is incorrect and what I inadvertently did when I said it did not work and got the same answer as original example:-
```
geom= rect1 - rect2
geom = rect1 + rect2
```
But doing this works as intended: -
```
geom = rect1 - rect2
geom = geom + rect2
```

So in effect whats going on is it's a compound geometry with the two individual geometries, but it is maybe not doing the union of them (to 'flatten' the geometry to a single geometry), so it double counts the area or something in the plastic caculation?

**Comment by robbievanleeuwen** [comment] 2022-02-20 13:09
> It sounds like my hypothesis was correct: that by following the subtractive modelling procedure, the correct result is calculated. When geometries are overlap, however, you do not have the correct result because you in fact have two overlaid rectangles and not two embedded rectangles. Am I correct in this understanding?

Yes I believe this is correct. When you dive into the plastic algorithm and plot each geometry after the section is split this is what appears to be happening.

While the modelling approach may not be the most correct, there is an issue in that interrogating the geometric results would lead you to believe their isn't an issue. Further I'm not sure what is the best way to build this geometry? I note that @Agent6-6-6's code worked with:

```python
rect2 = ps.rectangular_section(d=100, b=100).shift_section(0, 500)
```

However when this is changed to the original:

```python
rect2 = ps.rectangular_section(d=100, b=100).shift_section(100, 450)
```

the code will not run as there is a hole generated and sectionproperties is expecting two different materials.

**Comment by connorferster** [comment] 2022-02-26 22:46
Working on this...

**Comment by connorferster** [comment] 2022-02-27 23:43
My solution for this is to test to see if there are any overlapping geometries in the shapely geometry. If so then prior to calculating the plastic properties, warn the user (but do not stop the calculation) that the plastic properties may be incorrect because the overlapping regions will be double counted in the calculation. Guide the user to use "subtractive modelling" and point them to the "Advanced Geometry" page in the docs for more information.

**Comment by connorferster** [comment] 2022-02-27 23:46
By using two analysis methods (shapely + FEM) and because these two geometry processors interpret overlapping geometries differently, I think this problem will be inevitable. Overlapping geometry creates ambiguity (did the user intend for "geometry 1" to take precedence or "geometry 2"?). I think the best way to deal with this issue (for now) is to post a warning and guide the user to a better solution.

**Closed** 2022-02-28 00:36 UTC
Labels: bug
