### ISSUE TITLE
Switch over to triangle

### ISSUE THREAD

**Issue by robbievanleeuwen** [robbievanleeuwen/section-properties#24] opened 2020-05-25 03:02 UTC
Meshpy creates a lot of issues for users - will triangle work?

**Comment by Spectre5** [comment] 2021-01-09 18:31
It seems that some users are having issues with meshpy (#42, among others).  This seems to be one of the reasons to switch to triangle.  But, since meshpy is using triangle anyway, why do we think that using triangle would actually fix the random crash issue?  Meshpy does indicate that the triangle it includes has some minor changes, but I doubt it makes a minor change that would cause the issue.

Do we have a minimum working example that causes issues for multiple people?  If it crashes for me, I can try to dig a little deeper and see if I can debug it closer.  Perhaps the issue is about some poor input geometry that we can add a check/correction for in sectionproperties.

This said, I'm not opposed to switching to triangle at all.  But I'm not sure that it will magically fix the random crashes that some people have experienced.

@connorferster - maybe you have a minimum working example that regularly crashes?  Ideally one that works with current master, but one that works with your shapely changes is fine too.

**Comment by Spectre5** [comment] 2021-01-09 18:45
As an example, I see that the mesh is built using the code below.  Maybe the `min_angle` or `mesh_order` used here isn't good for some geometries?  At the least, I think these should probably be keyword arguments so that a user could change them.  Probably just accept `**kwargs` and pass that to the `build` method.

```
mesh = triangle.build(
    mesh, min_angle=30, mesh_order=2, quality_meshing=True,
    attributes=True, volume_constraints=True)
```

**Comment by connorferster** [comment] 2021-01-10 00:07
Hi all,

Have taken a break from sectionproperties this week. Will try and get back into it this weekend. Have been developing an application at work and it has taken a lot of my brain. 

I will take a look at the geometry and see if how that contributes to the problem. I found it odd because I was getting this result off of the rectangular section test, which I thought would be predictable. Will investigate further and see what I can find out. 

Agreed, if both meshpy and triangle are wrapping Triangle, then I don't know what the difference will be, unless, as @Spectre5 points out, the call to triangle itself may require some tweaking. I think it would be nice if we can make meshpy work but I think I will need to learn more about how Triangle works. 

Part of my ambition for working on a shapely interface is to have the geometry "just work" and not require detailed clean-up prior to meshing. I just had a read of the "Troubleshooting" page on the Triangle site and it seems helpful. I will review the problems I am having in more detail and report back: [http://www.cs.cmu.edu/~quake/triangle.trouble.html](http://www.cs.cmu.edu/~quake/triangle.trouble.html).

**Comment by Spectre5** [comment] 2021-01-10 00:17
Very weird that you would see the issue with the rectangle test!  That makes me think that it must be something related to the computer setup or the triangle library.  Maybe the wrong binary for you system gets installed from pypi or something?

I think using the triangle binary directly with an input file that causes issues is a very good idea.  Just submit it to the triangle binary many times and see if it crashes.  If so, use the troubleshooting page to debug.  That removes sectionproperties, meshpy, and the python interface to triangle all out of the equation.

I agree that removing all/most of the section clean-up is a huge upside to using shapely!

**Comment by aegis1980** [comment] 2021-01-10 06:36
[https://github.com/PyMesh/PyMesh/issues/115#issuecomment-412429474](https://github.com/PyMesh/PyMesh/issues/115#issuecomment-412429474)

PyMesh author describes here how to debug C++ parts of PyMesh, for an issue which seems quite similar. Somewhat fearful of diving into C++ meshing code but will try and give it a go and report in due course (since it is a bit of a show-stopper on what I am trying to do ;) )

**Comment by connorferster** [comment] 2021-01-10 07:34
PyMesh? Meshpy? What is real life?!?!

**Comment by aegis1980** [comment] 2021-01-11 05:55
@connorferster Ha. Dammit. Sorry, my bad. And I was going to spend tomorrow 'trying' to fix the wrong meshing library. Phew!

**Comment by Spectre5** [comment] 2021-01-11 17:17
Yup, probably the same root cause!  I'm guessing that there is certain inputs or features that triangle doesn't like and are making their way to it.  I still think using triangle directly with an input that fails is the best place to start.

**Comment by Czarified** [comment] 2021-01-11 19:09
I haven't had these issues, and I've been running and meshing rectangular geometry in my Hypothesis testing setup repeatedly. Sometimes I will lock up all system resources, but I was assuming that was because it tried to mesh at too small a size (as a result of Hypothesis bounds). It's never errored out when I ran, and since limiting the hypothesis bounds I have no issues.

**Comment by Spectre5** [comment] 2021-01-11 19:33
I haven't either, although I really haven't used it extensively yet.  Again, maybe it is something related to computer setup.

What system are people running?  I'm on Ubuntu 20.04.

**Comment by connorferster** [comment] 2021-01-11 20:47
Windows 10

**Comment by connorferster** [comment] 2021-01-11 20:47
Will giving this a look once I fix up the doc strings on the new classes and functions (next!)

**Comment by robbievanleeuwen** [comment] 2021-01-19 12:17
Hi all,

A bit late to the party here, but will try to clarify a few things:

1) The desire to switch to the python library `triangle`, is solely to address the installation issues a lot of users face (largely windows users, but here have also been issues experienced on unix systems as well).
2) I believe the segmentation errors some users are getting are due to corrupt geometry being passed to the c++ triangle routine, but it could also be related to faulty installation issues of `meshpy` (maybe this is what @connorferster is experiencing with the rectangle test?)
3) In essence both python libraries `triangle` and `meshpy` do exactly the same thing and use the same algorithm, but I believe `triangle` is more desirable because of the following (discussed in #22):
- fewer end-user installation issues (meshpy windows installation cannot easily be automated; requires c++ compiler)
- lighter weight dependency (meshpy also handles gmsh & some 3d mesh tools)
- more actively maintained

Robbie

**Comment by aegis1980** [comment] 2021-01-27 06:13
Have been mulling over & playing around with the Triangle issue. Technically, the particular issues I was having meshing relatively complex imported DXFs (aluminium extrusions with screw flutes etc) can be addressed by tinkering with geometry and meshing settings. (Python) Triangle gives a more accessible way of doing this and throws a python exception so you can go around again with different settings. MeshPy just spits a dummy.
Frankly, though I am a little reluctant to spend more time on it, because of the 'license' on the original C++ Shewchuk Triangle code, which does not quite marry up with the MIT one on this repo:
```
Please note that although Triangle is freely available, it is copyrighted by the author and may not be sold or included in commercial products without a license.
```
I was not going to be just calculating section properties for fun ;) Pretty sure I speak for other end users... 
I have has a look around for alternatives with no luck yet. 
Thoughts? Am I just being a kill-joy?

**Comment by connorferster** [comment] 2021-01-30 17:37
I believe that the "sold or included in commercial products" would only cause a problem if sectionproperties had an option for a "paid" version or someone used sectionproperties in their paid version of something else. Internal corporate use does not generally trigger a breach of license in these instances. This is similar to the Qt license, I believe.

**Comment by connorferster** [comment] 2021-01-30 17:47
From the license in the source of triangle.c:

Private, research, and institutional use is free.

Also:

If you are not directly supplying this code to a   customer, and you are instead telling them how they can obtain it for free, then you are not required to make any arrangement with me.

**Comment by Spectre5** [comment] 2021-01-30 18:38
Thanks for looking into it, that is my understanding too.  It would be illegal, I believe, to use triangle (and thus sectionproperties) in your own "cross section analysis" tool that you then sold to customers.  At least doing so without the caveat that Connor mentions above.

And whatever licenses issues there are or are not with triangle, that applies to the current code base since it uses meshpy, which uses triangle anyway.

**Comment by Spectre5** [comment] 2021-01-30 18:41
Are people still having issues with Triangle crashes?  If so, please indicate what system you use.  Maybe it is only any issues on Windows, which might provide some information to consider when debugging.  It can't be only a geometry issue since @connorferster has had issues even using a simple rectangle.

**Comment by robbievanleeuwen** [comment] 2021-01-30 23:53
The only reports that I have personally received related to installation issues (only windows platforms) & geometry errors. I would be interested to see if @connorferster got the same issues if the python package triangle was used in place of meshpy.

**Comment by connorferster** [comment] 2021-01-31 22:47
@"everybody" (not a tag, but still)

It *seems* that the problem I was having may have been connected to the way I generated the points and facets. I had the first point in the perimeter also as the last point in the perimeter. I fixed this and the problem seems to have gone away. 

Now, I am able to get test_rectangle.py to consistently run in pytest and I no longer have my issues when creating the mesh in Jupyter when also using matplotlib to `.plot_geometry()`. Great news.

Additionally, my tests were crashing because of `PlasticSection`: I had not reviewed it or updated it yet to see if there were inconsistencies with the new pre-processor. However, my intention is to fit the new pre-processor into the existing `CrossSection` and analysis interface so it should not require updating. 



I am however getting some funny values when calculating g

**Comment by Spectre5** [comment] 2021-02-01 00:08
awesome, good to hear!

**Comment by connorferster** [comment] 2021-12-30 23:53
Completed in #153.

For casual interest, I did a quick "benchmark" test between `triangle` and `meshpy`. I performed the test by first running the test code in one cell (while on the "triangle..." branch), I switched branches, reloaded the imports (with autoreload enabled), and re-ran the same code in a separate cell.

Comparison can be viewed here: https://gist.github.com/connorferster/74c39da3da2710315921d95bc67eb03d

Seems to be a slightly improvement in meshing by using `triangle`!

**Closed by connorferster** 2021-12-30 23:53 UTC
Labels: enhancement, v2+
