### ISSUE TITLE
Unexpected behavior calculating 2nd Moments of Area (.get_ic) with Material

### ISSUE THREAD

**Issue by aedificatio** [robbievanleeuwen/section-properties#272] opened 2023-04-28 10:59 UTC
Hi,  First a big complement for the great work that has been done with sectionproperties.

**Describe the bug**
Unexpected results for `.get_ic()` when using materials.
Both the documentation and the Docstring advertise the result being the second moments of area around the centroidal axis. There is NO mention of weighted results by materials.
The function returns I (ixx, iyy, ixy) when no material is applied and E times I (EI) when materials are applied. In my opinion this is inconsistent and unexpected behavior.

**Expected results**
`.get_ic()` always returns the second moments of area based on the geometry

**Additional context**
For a compound section the most accurate parameter would be EI. The concept of weighted results only relates to a compound section which includes different materials. The user could simply compute Eeff or Ic;eff.
I think the results of `.get_ic()` should only return the second moments of area based on the geometry. If the result is ambiguous because of different materials it could raise a warning, but still compute Ic based on the geometry.
In https://sectionproperties.readthedocs.io/en/latest/rst/post.html#how-material-properties-affect-results it is explained in more detail. The issue (or related) is also mentioned in #6 #16 #76 and #207. As a workaround an E-mod of 1 could be used or no material at all.

**Proposed solution**
*	`.get_ic()` only returns the geometric values of a (compound) section regardless of material
*	if different materials are being applied maybe raise a warning but still compute Ic
*	implement something like `.get_EI()` or `.get_EIeff()` to get the weighted result of a (compound) section

if the above is not implemented then please adjust the documentation to reflect the real behavior.

Kind regards.

**Comment by ccaprani** [comment] 2023-05-31 09:46
Hi @aedificatio ; not @robbievanleeuwen, but a contributor & interested engineer. I suspect you haven't gotten much response because the tone of your message comes across a little strong; I'm sure you didn't mean it that way.

It's certainly not dangerous to return material-weighted section properties. Indeed, this is the expected behaviour for any structural engineering application I can think of. 

Is there a structural engineering use-case for returning the unweighted properties for a composite section?

Nevertheless, if a user requires the geometric properties of a composite section without reference to any material weighting, then the materials can be set equal; or a nominal material of `E = 1` can be used, as you note. I wouldn't describe this as a workaround; it's just using the software to obtain the results of interest.

I think the key point is that the software is not inherently dangerous, and it's reasonable to expect users to know how to interpret the results. Adding warnings for regular use-cases then seems unnecessary.

**Comment by Spectre5** [comment] 2023-05-31 20:28
For what it's worth, I agree on this.  I think having a separate function for the moment of inertia and EI makes more sense and this behavior certainly caught me by surprise the first time too.  Plus, you could then call get_ei() for a section with only 1 material and get EI as well.

**Comment by robbievanleeuwen** [comment] 2023-06-11 12:23
Hi @aedificatio, @ccaprani and @Spectre5.

Apologies for the delayed response here. I spent a bit of time working on an update to ``sectionproperties`` at this start of this year (see #277), but life got in the way before I could close everything out! I'm now hoping to get this over the line in the next month 🤞

As you say, the documentation is unclear and it has been an issue for other users, so thank you for bringing this up. I am open to changes if it means that ``sectionproperties`` is easier for everyone to use.

I updated the documentation for these ``get`` methods at the start of the year to include a note about material properties, see [here](https://sectionproperties.readthedocs.io/en/hypermodern/gen/sectionproperties.analysis.section.Section.html#sectionproperties.analysis.section.Section.get_ic), however this maintains the previous behaviour which has been identified as problematic.

This would be a breaking change, so I'd like to proceed with caution and avoid previous code to have drastically different results, e.g. code developed to date expecting to receive ``EI`` from ``get_ic()`` would receive ``I`` without any material properties applied, which could happen without users being aware. This would introduce big errors for users upgrading to ``v3.0`` that aren't aware of all the changes - a bigger risk, I think, than what currently exists.

Here is a proposed solution, very happy to hear thoughts and other suggestions (also pinging @connorferster to see if you have any thoughts?):
- ``get_ic()`` returns (``ixx_c``, ``iyy_c``, ``ixy_c``) as long as the ``DEFAULT_MATERIAL`` <ins>is</ins> used (i.e. no material properties are applied), otherwise raises an error advising the user to use ``get_eic()``
- ``get_eic()`` returns (``eixx_c``, ``eiyy_c``, ``eixy_c``) as long as the ``DEFAULT_MATERIAL`` <ins>is not</ins> used (i.e. material properties are applied), otherwise raises an error advising the user to use ``get_ic()``
- This would also apply to other methods, such as ``get_ig()``, ``get_z()``, ``get_j()`` etc.

**Comment by connorferster** [comment] 2023-06-11 17:00
I agree that a change should be made and I like @robbievanleeuwen's proposed solution. By raising an error, it forces the user to employ the correct method for their context. It is a good application of "explicit is better than implicit" which is especially desirable in engineering!

While it would be desirable to correct this without introducing a breaking change, I don't see a way around that.

**Comment by connorferster** [comment] 2023-06-11 17:04
If this is going to trigger a v3.0.0, are there any other breaking changes that could be made at the same time? Maybe we could catch them all at once? 

Nothing immediately comes to mind right now but thought I would pose the question. I have a bit of time now over the summer to do some work on this, if so.

**Comment by connorferster** [comment] 2023-06-11 17:05
Also @aedificatio, thank you for the compliment!

**Comment by robbievanleeuwen** [comment] 2023-06-12 13:34
Hi @connorferster thanks for the feedback!

> If this is going to trigger a v3.0.0, are there any other breaking changes that could be made at the same time? Maybe we could catch them all at once?

I've tried to create a relatively exhaustive list in #277.

**Comment by Agent6-6-6** [comment] 2023-06-25 03:42
I must admit this really confused me at the beginning, partially because the documentation on what was actually being returned wasn't that clear (things may have improved, but since it keeps coming up potentially it needs some further work).  

I was expecting once E starts is defined for a material or materials that I'd be getting a transformed moment of inertia for example based on one of the materials (not that it would return a weighted E*I). I still don't quite understand the usefulness of using the weighted value and when it would be utilised in practical design.

Agree with the error being returned, should address people thinking the get_ic() method returns the actual moment of inertia when materials are applied.

I also think a transformed area/moment of inertia might also be a useful addition, define as an input what material you want the values returned in.

**Comment by robbievanleeuwen** [comment] 2023-09-24 08:23
New PR #287 attempts to close this issue. Refer notes in that PR for chosen implementation.

**Comment by robbievanleeuwen** [comment] 2023-09-28 01:30
Hi all, this change has been merged into the development PR. If you are interested in reviewing the changes, you can see the PR docs [here](https://sectionproperties--277.org.readthedocs.build/). More specifically:

- [Updated `get` methods](https://sectionproperties--277.org.readthedocs.build/en/277/user_guide/results.html#retrieving-section-properties) grouped by analysis type.
- Updated section on [how material properties affect results](https://sectionproperties--277.org.readthedocs.build/en/277/user_guide/results.html#how-material-properties-affect-results)
- New [example](https://sectionproperties--277.org.readthedocs.build/en/277/examples/results/get_results.html) highlighting how to use the `get`  methods.

Feel free to add any comments you have here. If there is nothing further, I will close this issue in a few days :)

**Closed** 2023-10-03 02:12 UTC
Labels: engineering, documentation
