### ISSUE TITLE
CompoundGeometry meshing failing

### ISSUE THREAD

**Issue by normanrichardson** [robbievanleeuwen/section-properties#112] opened 2021-10-21 05:29 UTC
**Describe the bug**
Under certain conditions, the `CompoundGeometry` mesh creation step (`geometry.create_mesh`) is failing. 

**To Reproduce**
```python
import sectionproperties.pre.sections as sections
from sectionproperties.analysis.cross_section import Section

s1 = sections.rectangular_section(1,1)
s2 = sections.rectangular_section(0.5,0.5).shift_section(1,0.25)

geometry = sections.CompoundGeometry([s1,s2])
geometry = geometry.rotate_section(angle=30, rot_point='center')

geometry.plot_geometry()
geometry.create_mesh(mesh_sizes=[0.2, 0.1])
section = Section(geometry)
section.display_mesh_info()
```
[triangle.build](https://github.com/robbievanleeuwen/section-properties/blob/b661bb093497d819bcbdf0e8be3028872c202df3/sectionproperties/pre/pre.py#L115) produces errors in `geometry.create_mesh(mesh_sizes=[0.2, 0.1])`: 
```
Internal error in segmentintersection():
  Topological inconsistency after splitting a segment.
  Please report this bug to jrs@cs.berkeley.edu
  Include the message above, your input data set, and the exact
    command line you used to run Triangle.
```

In more extreme cases such as [example_mirr_rot.py](https://github.com/robbievanleeuwen/section-properties/blob/b661bb093497d819bcbdf0e8be3028872c202df3/sectionproperties/examples/example_mirr_rot.py) (after updating to run with v2) the process crashes.

Interestingly if the rotation step is either 0, 90, 180, ... the meshing is successful. For example,
```python
import sectionproperties.pre.sections as sections
from sectionproperties.analysis.cross_section import Section

s1 = sections.rectangular_section(1,1)
s2 = sections.rectangular_section(0.5,0.5).shift_section(1,0.25)

geometry = sections.CompoundGeometry([s1,s2])
geometry = geometry.rotate_section(angle=90, rot_point='center')

geometry.plot_geometry()
geometry.create_mesh(mesh_sizes=[0.2, 0.1])
section = Section(geometry)
section.display_mesh_info()
```
```
Mesh Statistics:
--48 nodes
--17 elements
--2 regions
```

**Expected behaviour**
Meshing step completing.

**Additional context**
After some investigation, I think it is because the triangle is having a hard time with the facets:
```python
import sectionproperties.pre.sections as sections
from sectionproperties.analysis.cross_section import Section

s1 = sections.rectangular_section(1,1)
s2 = sections.rectangular_section(0.5,0.5).shift_section(1,0.25)

geometry = sections.CompoundGeometry([s1,s2])
print(f"points: {geometry.points}")
print(f"facets: {geometry.facets}")
```
```
points: [[0.0, 0.0], [1.0, 0.0], [1.0, 1.0], [0.0, 1.0], [1.0, 0.25], [1.5, 0.25], [1.5, 0.75], [1.0, 0.75]]
facets: [[0, 1], [1, 2], [2, 3], [3, 0], [4, 5], [5, 6], [6, 7], [7, 4]]
```
These are the facets of the [individual geometries](https://github.com/robbievanleeuwen/section-properties/blob/b661bb093497d819bcbdf0e8be3028872c202df3/sectionproperties/pre/sections.py#L1479-L1483) and I think the meshing would prefer the combined shape facets:
```
points: [[0.0, 0.0], [1.0, 0.0], [1.0, 1.0], [0.0, 1.0], [1.0, 0.25], [1.5, 0.25], [1.5, 0.75], [1.0, 0.75]]
facets: [[0, 1], [1, 4], [4, 7], [7, 2], [2, 3], [3, 0], [4, 5], [5, 6], [6, 7], [7, 4]]
```
So:
```python
import sectionproperties.pre.sections as sections
from sectionproperties.analysis.cross_section import Section

s1 = sections.rectangular_section(1,1)
s2 = sections.rectangular_section(0.5,0.5).shift_section(1,0.25)

geometry = sections.CompoundGeometry([s1,s2])
geometry_aug = sections.CompoundGeometry.from_points(
    geometry.points,
    [[0, 1], [1, 4], [4, 7], [7, 2], [2, 3], [3, 0], [4, 5], [5, 6], [6, 7], [7, 4]],
    geometry.holes,
    geometry.control_points
)
geometry_aug = geometry_aug.rotate_section(angle=30, rot_point='center')

geometry_aug.plot_geometry()
geometry_aug.create_mesh(mesh_sizes=[0.2, 0.1])
section = Section(geometry_aug)
section.display_mesh_info()
```
```
Mesh Statistics:
--52 nodes
--19 elements
--2 regions
```

**Comment by connorferster** [comment] 2021-11-03 05:21
@normanrichardson Thanks for finding this. Am going to investigate.

**Comment by connorferster** [comment] 2021-11-14 04:01
@normanrichardson, yes, I see what's happening here. When a transformation is performed on this geometry, we get a floating point error gap between the two shapes. This can be observed by using their `_repr_svg_()` as shown below:
![image](https://user-images.githubusercontent.com/38441489/141666554-646dfbee-848c-4f51-bfdc-0f08d49f162e.png)

Where the red shapes indicate an "invalid" geometry (in shapely's eyes, not sectionproperties), because the geometries share an edge, and the green shapes indicate a "valid" geometry because they are not actually touching.

Currently, the code in the sectionproperties transformation methods (e.g. `.rotate_section()`) iterate through each geometry and performs the transformation on each geometry separately. I thought, "Why not just perform the transformation on the MultiPolygon instead of each individual Polygon?" So, I tried that but it did not fix the problem. 

It seems to be an inconsistent problem, as one might expect from a floating point error. I tried iterating the rotation from 1 - 360 degrees and displaying the svg each time. It seems that it's only on certain angles where I get green geometries instead of red geometries. 

I see your solution and that makes sense. It falls in the category of what I call "advanced geometry" where the user has to override the default shapely behaviour to make it give you the section you want (with nodes and facets exactly where you want them). I will have to think more on this.

**Comment by connorferster** [comment] 2021-11-14 07:04
@normanrichardson Ah! Yes! It is just like the example I give in the "Advanced Geometry" section in the docs. This is excellent because the example I used does not cause an error if done in the conventional way. HOWEVER! This example DOES cause an error which makes for a better example. 

Here is the way to model the geometry to not cause a mesh error:
```python
import sectionproperties.pre.sections as sections
from sectionproperties.analysis.cross_section import Section

s1 = sections.rectangular_section(1,1)
s2 = sections.rectangular_section(0.5,0.5).shift_section(1,0.25)


# geometry = sections.CompoundGeometry([s1,s2])
geometry = ((s1 - s2) | s1) + s2
geometry_rot = geometry.rotate_section(angle=30, rot_point='center')

geometry_rot.plot_geometry(labels=["points", "facets"])
geometry_rot.create_mesh(mesh_sizes=[0.2, 0.1])
section = Section(geometry_rot)
section.display_mesh_info()
```

![image](https://user-images.githubusercontent.com/38441489/141671028-6c8c7824-b432-48fc-b1b4-4eb0d63909c9.png)

**Comment by connorferster** [comment] 2021-11-14 07:12
So, I should update the example in the Advanced Geometry with this example to illustrate what a meshing error looks like, clues on how to identify the cause (disconnected geometry), and how to model it to remedy it.

**Comment by normanrichardson** [comment] 2021-11-15 23:31
@connorferster thanks I see, that seems to work and the mesher can find the common edge. 

Are there any drawbacks to performing these operations in the `CompoundGeometry` constructor? Looking at the overridden operators I'm guessing that if two geometries share a domain with 2 different materials, then the "1st" material will be assigned to that domain.

**Comment by connorferster** [comment] 2021-11-16 05:46
@normanrichardson,
Using the `CompoundGeometry` constructor should be the same as using the `+` operator. Here is an example:

```python
import sectionproperties.pre.sections as sections
from sectionproperties.pre.pre import Material
from sectionproperties.analysis.cross_section import Section

mat_1 = Material("Material 1", 200e3, 0.3, 300, "yellow")
mat_2 = Material("Material 2", 72e3, 0.25, 100, "purple")

s1 = sections.rectangular_section(1,1)
s2 = sections.rectangular_section(0.5,0.5).shift_section(1,0.25)
s1.material = mat_1
s2.material = mat_2
geometry_fixed = sections.CompoundGeometry([(s1 - s2), s2])
geometry_fixed_rotated
```

![image](https://user-images.githubusercontent.com/38441489/141927583-d55c30cf-4481-4072-a4a9-a6cb40187a74.png)

The materials assigned to each geometry stay with the geometry and then each gets added to the `CompoundGeometry`. 

The other operators, `|`, `-`, `&`, `^` do take the first geometry's material as precedence when the geometries become combined but the `+` operator just keeps both geometry material assignments.

**Comment by robbievanleeuwen** [comment] 2021-11-18 05:26
Thanks for finding @normanrichardson and thanks for investigating @connorferster!

Now that the docs have been updated are we happy to close this one?

**Closed** 2021-11-18 05:54 UTC
Labels: documentation
